name: internal_network
description: internal_network project.
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ">=7.0.0"
  dio: ">=5.9.0"
  mqtt_client: ">=10.11.1"
  mqtt5_client: ">=4.14.0"
  
  internal_core: 
    path: ../core

dev_dependencies:
  flutter_lints: ">=6.0.0"

jsonToDart: 
  typeChecking: false
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false
  mergeArrayApproach: false #default: true
